### PR TITLE
Unique requirements

### PR DESCRIPTION
**Pull request by Withington**
We need to discuss and agree on a unique set of requirements and merge it in to master. Github provides Pull Requests for such discussion so I’ve set up this unique_requirements branch and opened this Pull Request so we can do that. Please add your comments and your commits to this branch. Once we’ve agreed (deadline TBA), one of us can merge the pull request in to master.

References - 

Github - “Code review is an essential part of the GitHub workflow. After creating a branch and making one or more commits, a Pull Request starts the conversation around the proposed changes. Additional commits are commonly added based on feedback before merging the branch.” https://github.com/features/projects/codereview

TMA03 Q2a - “Review the functional requirements your group discussed and resolve any remaining differences so that you have an agreed set of unique requirements.”

Arosha Bandara “As part of the TMA03 activity you are asked to merge your branches back into the master, so as part of this you will need to finalise any changes to the functional requirements and resolve conflicts as part of the merge.  
As you have noted, you can use some of the time this week to agree on a final set of functional requirements.” https://learn2.open.ac.uk/mod/forumng/discuss.php?d=2122325#p15552098

### CODE REVIEW

**Comment by Withington** [comment]
Comments on the changes I made - 

FR-1 and FR-24 both concern producing a confirmation. Requirements shouldn't mention a specific technology. FR-24 deleted and FR-1 updated to remove reference to a specific technology.

FR-11 removed, FR-20 updated, FR-28 retained. The group elicited requirements for both ad-hoc and time-triggered management reports. This results in two requirements, FR-20 and 28, to ensure that a developer won’t miss either.

**Comment by ccezarr** [comment]
Nice, suggested changes are in line with mine.

**Comment by Withington** [comment]
Thanks @ccezarr .

**Comment by airwalk225** [comment]
Pardon my ignorance, I've never used Githubs pull feature before. Do I just pull this as a normal branch with in my Git client? And then add the comments via the webpage? Or does my commit message become the comment?

**Comment by Withington** [comment]
@airwalk225 yes, you've done it. You can commit and then push to this branch, your commit messages then show up in this conversation and you can also add extra comments right here.

**Comment by samb8s** [comment]
First, I'm not going to merge your pull request, but I do approve it!

Personally I think we could have handled the management report requirements better. My suggestion would be:
 - have a requirement (which FR-11 did) for "creating reports"
 - have a requirement for scheduling reports, which references FR-11
 - have a requirement for ad-hoc reporting, which references FR-11

This seems more logical than having two different requirements for reports, as it keeps reporting requirements in one place and maintains one "source of truth" rather than two.
However, since this isn't a huge deal, and I don't think we get any credit for this, I'm happy to use what you've gone with, if others are.

**Comment by Withington** [comment]
Thanks @samb8s.

**Pull request merged**
